### ISSUE TITLE
A random query

### ISSUE THREAD

**Issue by tasdikrahman** [floriankrueger/Manuscript#2]
Hey there @floriankrueger . Loved Manuscript. 

A Quick question. What are you using to create this 

![https://raw.githubusercontent.com/floriankrueger/Manuscript/assets/manuscript.png](https://raw.githubusercontent.com/floriankrueger/Manuscript/assets/manuscript.png)

Looks super awesome. 

Best.

**Comment by floriankrueger** [comment]
Hi @prodicus. I'm glad to hear you like the lib and the logo.

I created the logo myself using [Pixelmator](http://www.pixelmator.com/mac/), but that's rather arbitrary and could have been done in any graphics program. You can find the .pxm files in the [assets branch](https://github.com/floriankrueger/Manuscript/tree/assets/pxm). The fonts are [Deibi](https://www.behance.net/gallery/deibi-v10-free-font/346023) and [Mohave](https://www.behance.net/gallery/8668939/Mohave-Typefaces) which are both free (and I probably should add some attribution somewhere 🤔). The colors are from [FlatUI Colors](http://flatuicolors.com).

I hope that helps!

**Comment by tasdikrahman** [comment]
Sad that Pixelmator is not available for Linux systems. Looks like I will have to go with Gimp.

Thanks for your time @floriankrueger  :)

**Comment by floriankrueger** [comment]
Not a problem, I would be interested in whatever you create. Closing the issue for now.

**Comment by tasdikrahman** [comment]
Sure thing.
