### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [floriankrueger/Manuscript#5]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by floriankrueger** [comment]
Hi @lfarah thanks for the issue. I migrated the code on a release branch (release/3.0.0). Please take it for a testflight and hit me with any issues you encounter.

**Comment by lfarah** [comment]
Hey @floriankrueger, got an error when building the example app:

```
'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'Main' in bundle NSBundle
```

**Comment by floriankrueger** [comment]
absolutely right, Xcode added the "Main Interface" setting again .. please see ee14b9d for the fix and tell me again if it works for you now.

**Comment by floriankrueger** [comment]
@lfarah so I just published a third preview of the framework. If everything is working for you (it does for me) then I'd be happy to create a release this week.

**Comment by lfarah** [comment]
Hey @floriankrueger, sorry for the delay. I've been packed with work stuff and I didn't have time to take a look at it 😢

**Comment by floriankrueger** [comment]
not a problem, I did a release by now as I had the preview in production for some days without any issues. If you see anything, just tell me :D
